

--MATERIAS PARA LOS GRUPOS, SE DEBE CONSERVAR SIMPLICIDAD EN LA MATRICULA AL PRINCIPIO, PARA QUE SE VEA AQUI MAMALON,    PD:INSEERTAR MATERIAS MEDIO DE PELICULA DE DISNEY 
--PARA QUE AL ENSEñAR SE VEA AQUI ESOTERICO 
--INSERT INTO MATERIAS VALUES('AA123','ABECEDARIO ARABE-INDIO-AFRICANO','');



--PROFESORES A DAR CLASES
--INSERT INTO PROFESORES VALUES('SEX69','DOCTOR VALDOMERO ESPINOZA','6969696969','DOCTORVALDOMERO@TAXI.TURK','01/01/01');



--HORARIOS A DARSE
-- QUE SEAN COHERENTES SUS HORAS, ANDO VIENDO QUE SALGAN COMO EN LA PAGINA Y NO TODO DE ASI CACA 
--INSERT INTO HORARIOS VALUES('AA123','001C','SEX69','2025-12-12 09:00:00','2025-12-12 11:00:00','2025-12-12 07:00:00','2025-12-12 14:00:00','2025-12-12 13:00:00');


--ALUMNOS A INGRESAR
--INSERT INTO ALUMNOS VALUES('KBR','TURISMO xD','6','KEVIN KALEB DE JESUS MARIA',973,'DEREALDEJESUSYMARIA@KALEBK.COM','2025-03-25 00:00:00');




----GRUPOS A LOS QUE PROFESORES DAN CLASES 
--INSERT INTO MATERIASPROFESORES VALUES('SEX69','ALGO1');


--GRUPOS DE ALUMNOS
--EL ULTIMO ARGUMENTO ES A LIBRE ALBEDRIO,LMITADO A LONGITUD 5
--INSERT INTO GRUPOALUMNOS VALUES('BB456','KBR','ALGO1');





--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS
--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS
--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS
--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS--NUEVAS

---CALIFICACIONES
--INSERT INTO CALIFICACIONES VALUES('BB456','AA123',7,5,9,'AGO24-DIC24');